;
; File generated by cc65 v 2.19 - Git 62da869e4
;
	.fopt		compiler,"cc65 v 2.19 - Git 62da869e4"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_printf
	.export		_main

.segment	"RODATA"

S0001:
	.byte	$54,$68,$65,$20,$66,$69,$72,$73,$74,$20,$31,$30,$20,$6E,$61,$74
	.byte	$75,$72,$61,$6C,$20,$6E,$75,$6D,$62,$65,$72,$73,$20,$61,$72,$65
	.byte	$3A,$0A,$00
S0002:
	.byte	$25,$64,$20,$00
S0003	:=	S0001+33

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     decsp2
	lda     #<(S0001)
	ldx     #>(S0001)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	ldx     #$00
	lda     #$01
	jsr     stax0sp
L0002:	jsr     ldax0sp
	cmp     #$0B
	txa
	sbc     #$00
	bvc     L0006
	eor     #$80
L0006:	bpl     L0003
	lda     #<(S0002)
	ldx     #>(S0002)
	jsr     pushax
	ldy     #$05
	jsr     pushwysp
	ldy     #$04
	jsr     _printf
	ldx     #$00
	lda     #$01
	jsr     addeq0sp
	bra     L0002
L0003:	lda     #<(S0003)
	ldx     #>(S0003)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	jmp     incsp2

.endproc

